replicaCount: 2

image:
  repository: satishosk/tourism-react
  tag: prod-<BUILD_TAG> 
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30082

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: tourism.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
