apiVersion: v1
kind: Service
metadata:
  name: tourism-frontend-service
spec:
  type: NodePort
  selector:
    app: tourism-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
