replicaCount: 1

image:
  repository: satishosk/tourism-react
  tag: dev-<BUILD_TAG>
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30081

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: tourism-dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
