apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tourism-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OletiSatishKumar/Tourism_Infra.git
    targetRevision: HEAD
    path: helm/tourism-chart
    helm:
      valueFiles:
        - ../../env/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tourism-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
