apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tourism-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OletiSatishKumar/Tourism_website_Infra
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc  # Use Dev Cluster URL if external
    namespace: tourism-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
