name: Update Values for New Image

on:
  repository_dispatch:
    types: [update-values]

jobs:
  update-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Infra Repo
      uses: actions/checkout@v3

    - name: Update Dev values.yaml
      run: |
        IMAGE="${{ github.event.client_payload.image }}"
        REPO=$(echo "$IMAGE" | cut -d':' -f1)
        TAG=$(echo "$IMAGE" | cut -d':' -f2)

        sed -i "s|repository:.*|repository: ${REPO}|" env/dev/values.yaml
        sed -i "s|tag:.*|tag: ${TAG}|" env/dev/values.yaml

    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "Update image to ${{ github.event.client_payload.image }}"
        git push
