name: Update Infra

on:
  repository_dispatch:
    types: [update-infra]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Replace image tag in dev
        run: |
          TAG=${{ github.event.client_payload.image_tag }}
          sed -i "s|image: .*|image: oletisatishkumar/react-tourism:$TAG|g" dev/deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update dev image to $TAG"
          git push
